default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary: &development
    <<: *default
    database: starter_kit_development
    schema_format: sql
  cache:
    <<: *development
    database: starter_kit_development_cache
    schema_format: ruby
    migrations_paths: db/cache_migrate
  cable:
    <<: *development
    database: starter_kit_development_cable
    schema_format: ruby
    migrations_paths: db/cable_migrate

test:
  primary: &test
    <<: *default
    database: <%= ENV.fetch("E2E_PGDATABASE", "rails_api_starter_kit_test") %>
    schema_format: sql
  cache:
    <<: *test
    database: <%= ENV.fetch("E2E_PGDATABASE", "rails_api_starter_kit_test") %>_cache
    schema_format: ruby
    migrations_paths: db/cache_migrate
  cable:
    <<: *test
    database: <%= ENV.fetch("E2E_PGDATABASE", "rails_api_starter_kit_test") %>_cable
    schema_format: ruby
    migrations_paths: db/cable_migrate

production:
  primary: &production
    <<: *default
    database: starter_kit_production
    schema_format: sql
    host: <%= ENV.fetch("DB_HOST", "localhost") %>
    username: starter_kit
    password: <%= ENV["STARTER_KIT_DATABASE_PASSWORD"] %>
  cache:
    <<: *production
    database: starter_kit_production_cache
    schema_format: ruby
    migrations_paths: db/cache_migrate
  cable:
    <<: *production
    database: starter_kit_production_cable
    schema_format: ruby
    migrations_paths: db/cable_migrate
