import { test, expect, text, routes, uniqueEmail, password, signedIn } from "./fixtures"

test("register, confirm the mailed link, finish onboarding and reach the dashboard", async ({ page, api }) => {
  const email = uniqueEmail()
  await page.goto("/registration/new")
  await page.getByLabel(text("fields.name"), { exact: true }).fill("New Browser User")
  await page.getByRole("button", { name: text("stepper.next"), exact: true }).click()
  await page.getByLabel(text("fields.email"), { exact: true }).fill(email)
  await page.getByRole("button", { name: text("stepper.next"), exact: true }).click()
  await page.getByRole("checkbox").check()
  await page.getByRole("button", { name: text("stepper.next"), exact: true }).click()
  await page.getByRole("button", { name: text("auth.registration.submit"), exact: true }).click()
  await expect(page.getByText(text("auth.session.link_sent_title"))).toBeVisible()
  const path = await api.mailLink(email, "/magic-links/")
  await page.goto(path)
  await expect(page.getByRole("button", { name: text("auth.magic_link.confirm_submit"), exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem("starterkit:token"))).toBeNull()
  await page.getByRole("button", { name: text("auth.magic_link.confirm_submit"), exact: true }).click()
  await expect(page).toHaveURL(/\/onboarding\/edit$/)
  await page.getByLabel(text("fields.organization_name"), { exact: true }).fill("Browser Team")
  await page.getByRole("button", { name: text("stepper.next"), exact: true }).click()
  await page.getByRole("button", { name: text("onboarding.submit"), exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await expect(page.getByRole("button", { name: /Browser Team/ })).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(/\/dashboard$/)
})

test("request a magic link, sign in, sign out and refuse a used link", async ({ page, api, user }) => {
  await page.goto("/session/new")
  await page.getByLabel(text("fields.email"), { exact: true }).fill(user.user.email)
  await page.getByRole("button", { name: text("auth.session.send_link"), exact: true }).click()
  await expect(page).toHaveURL(/\/session\/check-your-email/)
  const path = await api.mailLink(user.user.email, "/magic-links/")
  await page.goto(path)
  await page.getByRole("button", { name: text("auth.magic_link.submit"), exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.getByRole("button", { name: new RegExp(user.user.email) }).click()
  await page.getByRole("menuitem", { name: text("nav.sign_out"), exact: true }).click()
  await expect(page).toHaveURL((url) => url.pathname === "/")
  expect(await page.evaluate(() => localStorage.getItem("starterkit:token"))).toBeNull()
  await page.goto(path)
  await expect(page.getByRole("alert")).toContainText(text("errors.api.magic_link_invalid"))
})

test("wrong password keeps the form usable, then the correct password signs in", async ({ page, createUser }) => {
  const user = await createUser({ withPassword: true })
  await page.goto("/session/new")
  await page.getByRole("tab", { name: text("auth.session.tab_password"), exact: true }).click()
  await page.getByLabel(text("fields.email"), { exact: true }).fill(user.user.email)
  await page.getByLabel(text("fields.password"), { exact: true }).fill("wrong-password")
  await page.getByRole("button", { name: text("auth.session.submit"), exact: true }).click()
  await expect(page.getByRole("alert")).toContainText(text("errors.api.invalid_credentials"))
  await expect(page.getByLabel(text("fields.password"), { exact: true })).toHaveValue("")
  await page.getByLabel(text("fields.password"), { exact: true }).fill(password)
  await page.getByRole("button", { name: text("auth.session.submit"), exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
})

test("optional onboarding can be skipped without renaming the workspace", async ({ page, api, createUser }) => {
  const user = await createUser({ onboard: false })
  const initial = (await api.bootstrap(user.token)).auth!.organization.name
  await signedIn(page, user)
  await expect(page).toHaveURL(/\/onboarding\/edit$/)
  await page.getByRole("button", { name: text("onboarding.skip"), exact: true }).click()
  await page.getByRole("button", { name: text("onboarding.submit"), exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  expect((await api.bootstrap(user.token)).auth!.organization.name).toBe(initial)
  expect(await api.call(routes.apiV1Onboarding.show(), undefined, user.token)).toMatchObject({ required: false })
})
