/** SPA paths live here and in the router; API paths come only from generated helpers. */
export const paths = {
  home: (locale = "en") => (locale === "en" ? "/" : `/${encodeURIComponent(locale)}`),
  legal: (slug: string, locale = "en") =>
    `${locale === "en" ? "" : `/${encodeURIComponent(locale)}`}/legal/${encodeURIComponent(slug)}`,
  invitation: (token: string) => `/invitations/${encodeURIComponent(token)}`,
  signIn: "/session/new",
  register: "/registration/new",
  checkEmail: "/session/check-your-email",
  dashboard: "/dashboard",
  onboarding: "/onboarding/edit",
  newOrganization: "/organizations/new",
  profile: "/settings/profile/edit",
  email: "/settings/email/edit",
  password: "/settings/password/edit",
  emailPreferences: "/settings/email-preferences/edit",
  sessions: "/settings/sessions",
  appearance: "/settings/appearance/edit",
  account: "/settings/account/edit",
  organization: "/settings/organization/edit",
  members: "/settings/members",
  billing: "/settings/billing",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminOrganizations: "/admin/organizations",
  adminTranslations: "/admin/translations",
  adminLegalDocuments: "/admin/legal-documents",
  adminAuditEvents: "/admin/audit-events",
} as const
